name: 🚀 Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      # Step 2: (Optional) Run build steps
      # Uncomment if your project requires build before deployment
      - name: Install dependencies
        run: npm install


      - name: Install PHP dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer install --no-dev --optimize-autoloader

      - name: Run migrations
        run: |
          php artisan migrate --force

      - name: Build project
        run: npm run build

      # Step 3: FTP Deploy
      - name: 📤 Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
