name: Deploy Site to test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, pdo, mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install PHP dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer install --no-dev --optimize-autoloader

      - name: Run Laravel optimizations
        run: |
          php artisan config:cache
          php artisan route:cache

      - name: Deploy Backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # deploy everything
          exclude: |
            **/node_modules/**
            **/.git*
